language: python
python:
  - 3.11
env:
  - ARTICLEMETA_SETTINGS_FILE=./config.ini
before_install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - python setup.py test
before_script:
  - cp ./development.ini-TEMPLATE ./config.ini
