version: '3'
services:
  articlemeta-restfulapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: my-articlemeta
    environment:
      ADMIN_TOKEN:
      LOGGING_LEVEL: DEBUG
      MONGODB_HOST:
      MONGODB_PORT:
      SENTRY_DSN:
    command:
        - gunicorn
        - --paste
        - config.ini
        - -w
        - '4'
        - -b
        - 0.0.0.0
    labels:
      io.rancher.container.pull_image: always
